import type { Atlas, EdgeRecord } from "./types.ts";

export function renderMarkdown(atlas: Atlas): string {
  const lines: string[] = [];
  lines.push(`# Codebase Map: ${atlas.repo.name}`);
  lines.push("");
  lines.push(`Generated by Cartograph on ${atlas.generatedAt}.`);
  lines.push("");
  lines.push("## Snapshot");
  lines.push("");
  lines.push(`- Files scanned: ${atlas.summary.files}`);
  lines.push(`- Import edges: ${atlas.summary.edges}`);
  lines.push(`- Modules: ${atlas.summary.modules}`);
  lines.push(`- External imports: ${atlas.summary.externalImports}`);
  lines.push("");

  lines.push("## How To Read This Repo");
  lines.push("");
  lines.push("Start with the entrypoints and hotspots. Entrypoints show where behavior begins; hotspots show files that are central, widely imported, or role-heavy.");
  lines.push("");

  lines.push("## Modules");
  lines.push("");
  lines.push("| Module | Files | Lines | Incoming | Outgoing | Roles |");
  lines.push("| --- | ---: | ---: | ---: | ---: | --- |");
  for (const module of atlas.modules.slice(0, 30)) {
    lines.push(`| \`${module.name}\` | ${module.files} | ${module.lines} | ${module.incoming} | ${module.outgoing} | ${formatRoles(module.roles)} |`);
  }
  lines.push("");

  lines.push("## Entrypoints");
  lines.push("");
  if (atlas.entrypoints.length === 0) {
    lines.push("No obvious entrypoints found yet.");
  } else {
    for (const file of atlas.entrypoints.slice(0, 20)) {
      lines.push(`- \`${file.path}\` - ${file.roles.join(", ")}`);
      for (const route of file.routes.slice(0, 5)) {
        lines.push(`  - ${route.method} ${route.path}`);
      }
    }
  }
  lines.push("");

  lines.push("## Hotspots");
  lines.push("");
  lines.push("| File | Score | Incoming | Outgoing | Roles |");
  lines.push("| --- | ---: | ---: | ---: | --- |");
  for (const hotspot of atlas.hotspots.slice(0, 20)) {
    lines.push(`| \`${hotspot.path}\` | ${hotspot.score} | ${hotspot.incoming} | ${hotspot.outgoing} | ${hotspot.roles.join(", ")} |`);
  }
  lines.push("");

  lines.push("## External Dependencies");
  lines.push("");
  const externalCounts = countExternalImports(atlas.edges);
  for (const [name, count] of externalCounts.slice(0, 30)) {
    lines.push(`- \`${name}\` used by ${count} file${count === 1 ? "" : "s"}`);
  }
  lines.push("");

  lines.push("## Next Questions");
  lines.push("");
  lines.push("- Which hotspot files do you not understand well enough to change confidently?");
  lines.push("- Which entrypoints map to your most important user workflows?");
  lines.push("- Which modules have high outgoing edges and should be documented first?");
  lines.push("- Which AI or AWS touchpoints need explicit runbooks?");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function formatRoles(roles: Record<string, number>): string {
  const entries = Object.entries(roles);
  if (entries.length === 0) return "";
  return entries.map(([role, count]) => `${role} (${count})`).join(", ");
}

function countExternalImports(edges: EdgeRecord[]): [string, number][] {
  const counts = new Map<string, number>();
  for (const edge of edges) {
    if (edge.kind !== "external-import") continue;
    const name = packageName(edge.specifier);
    counts.set(name, (counts.get(name) ?? 0) + 1);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

function packageName(specifier: string): string {
  if (specifier.startsWith("@")) {
    return specifier.split("/").slice(0, 2).join("/");
  }
  return specifier.split("/")[0];
}
